import api from "@/core/api/axios";

export const getWorkers = async () => {
  const res = await api.get("/workers/");
  return res.data;
};

export const getProjects = async () => {
  const res = await api.get("/projects/");
  return res.data;
};

export const getSitesByProject = async (projectId) => {
  const res = await api.get(`/sites/by-project/${projectId}`);
  return res.data;
};

export const createWorker = async (data) => {
  try {
    const res = await api.post("/workers/", data);
    return res.data;
  } catch (err) {
    console.error("Error creating worker:", err);
    throw err;
  }
};

export const deleteWorker = async (id) => {
  await api.delete(`/workers/${id}`);
};

// Download Excel template generated by backend
export const downloadTemplate = async () => {
  try {
    const res = await api.get("/workers/template-excel", {
      responseType: "blob",
    });

    const blob = new Blob([res.data], {
      type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    });

    const url = window.URL.createObjectURL(blob);

    const a = document.createElement("a");
    a.href = url;
    const date = new Date().toISOString().slice(0,10);
    a.download = `workers_template_${date}.xlsx`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);

    window.URL.revokeObjectURL(url);

  } catch (err) {
    console.error("Template download failed", err);
    throw new Error(
      "Failed to download template: " +
      (err?.response?.data?.detail || err.message)
    );
  }
};

export const bulkValidate = async (payload) => {
  const res = await api.post("/workers/bulk-validate", payload);
  return res.data;
};

export const bulkCreate = async (payload) => {
  const res = await api.post("/workers/bulk-create", payload);
  return res.data;
};