"""added a new col named timezone in sites

Revision ID: 00b4194905b7
Revises: 62fb9e299537
Create Date: 2026-04-01 04:09:07.241293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00b4194905b7'
down_revision: Union[str, Sequence[str], None] = '62fb9e299537'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sites', sa.Column('timezone', sa.String(), server_default='Asia/Riyadh', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sites', 'timezone')
    # ### end Alembic commands ###
