"""Made mobile number of worker unique

Revision ID: 267a95fcd832
Revises: 3991115ac1da
Create Date: 2026-03-09 20:05:38.488073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '267a95fcd832'
down_revision: Union[str, Sequence[str], None] = '3991115ac1da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'workers', ['mobile'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workers', type_='unique')
    # ### end Alembic commands ###
