"""Added column device_attendance_id in attendance_record

Revision ID: 2867a9506cf8
Revises: 7df67f81954e
Create Date: 2026-06-10 14:29:09.140320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2867a9506cf8'
down_revision: Union[str, Sequence[str], None] = '7df67f81954e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance_records', sa.Column('device_attendance_id', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'attendance_records', ['device_attendance_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'attendance_records', type_='unique')
    op.drop_column('attendance_records', 'device_attendance_id')
    # ### end Alembic commands ###
