"""Added is_deleted field in Worker,Site and Project

Revision ID: 38963876a4a9
Revises: 705b1060fb15
Create Date: 2026-02-23 21:47:53.067379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38963876a4a9'
down_revision: Union[str, Sequence[str], None] = '705b1060fb15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('sites', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('workers', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workers', 'is_deleted')
    op.drop_column('sites', 'is_deleted')
    op.drop_column('projects', 'is_deleted')
    # ### end Alembic commands ###
