"""update attendance record for multi-site support

Revision ID: 4f13cf40fda1
Revises: 13e376652934
Create Date: 2026-02-21 14:22:06.498277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f13cf40fda1'
down_revision: Union[str, Sequence[str], None] = '13e376652934'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance_records', sa.Column('check_in_site_id', sa.UUID(), nullable=False))
    op.add_column('attendance_records', sa.Column('check_out_site_id', sa.UUID(), nullable=False))
    op.alter_column('attendance_records', 'worker_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(op.f('attendance_records_site_id_fkey'), 'attendance_records', type_='foreignkey')
    op.create_foreign_key(None, 'attendance_records', 'sites', ['check_out_site_id'], ['id'])
    op.create_foreign_key(None, 'attendance_records', 'sites', ['check_in_site_id'], ['id'])
    op.drop_column('attendance_records', 'site_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance_records', sa.Column('site_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'attendance_records', type_='foreignkey')
    op.drop_constraint(None, 'attendance_records', type_='foreignkey')
    op.create_foreign_key(op.f('attendance_records_site_id_fkey'), 'attendance_records', 'sites', ['site_id'], ['id'])
    op.alter_column('attendance_records', 'worker_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('attendance_records', 'check_out_site_id')
    op.drop_column('attendance_records', 'check_in_site_id')
    # ### end Alembic commands ###
