"""Make checkout site_id nullable

Revision ID: 705b1060fb15
Revises: 4f13cf40fda1
Create Date: 2026-02-22 01:13:06.074225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '705b1060fb15'
down_revision: Union[str, Sequence[str], None] = '4f13cf40fda1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attendance_records', 'check_out_site_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attendance_records', 'check_out_site_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
