"""add boundary type polygon coords to site

Revision ID: 73599ae0e417
Revises: 23bc0e3f29f9
Create Date: 2026-03-11 21:12:43.289975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73599ae0e417'
down_revision: Union[str, Sequence[str], None] = '23bc0e3f29f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sites', sa.Column('boundary_type', sa.String(), server_default='circle', nullable=False))
    op.add_column('sites', sa.Column('polygon_coords', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sites', 'polygon_coords')
    op.drop_column('sites', 'boundary_type')
    # ### end Alembic commands ###
