"""added daily_working_hours and  OT Multiplier in worker table

Revision ID: 756af183ac30
Revises: c1d2e3f4a5b6
Create Date: 2026-03-13 22:56:44.831814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '756af183ac30'
down_revision: Union[str, Sequence[str], None] = 'c1d2e3f4a5b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workers', sa.Column('daily_working_hours', sa.Float(), nullable=True))
    op.add_column('workers', sa.Column('ot_multiplier', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workers', 'ot_multiplier')
    op.drop_column('workers', 'daily_working_hours')
    # ### end Alembic commands ###
