"""added employee_name to User model

Revision ID: a50d3d58a24d
Revises: 267a95fcd832
Create Date: 2026-03-10 00:44:44.485810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a50d3d58a24d'
down_revision: Union[str, Sequence[str], None] = '267a95fcd832'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('employee_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'employee_name')
    # ### end Alembic commands ###
