"""Added two more  field in Worker,Site and Project

Revision ID: ba96c81fb16d
Revises: 38963876a4a9
Create Date: 2026-02-23 23:31:34.676030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba96c81fb16d'
down_revision: Union[str, Sequence[str], None] = '38963876a4a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('projects', sa.Column('deleted_by', sa.String(), nullable=True))
    op.add_column('sites', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('sites', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('sites', sa.Column('deleted_by', sa.String(), nullable=True))
    op.add_column('workers', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('workers', sa.Column('deleted_by', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workers', 'deleted_by')
    op.drop_column('workers', 'deleted_at')
    op.drop_column('sites', 'deleted_by')
    op.drop_column('sites', 'deleted_at')
    op.drop_column('sites', 'created_at')
    op.drop_column('projects', 'deleted_by')
    op.drop_column('projects', 'deleted_at')
    # ### end Alembic commands ###
