"""added updated_at field in worker,site and project

Revision ID: d01c84056e56
Revises: 00b4194905b7
Create Date: 2026-04-23 13:14:55.106307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd01c84056e56'
down_revision: Union[str, Sequence[str], None] = '00b4194905b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('sites', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('workers', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workers', 'updated_at')
    op.drop_column('sites', 'updated_at')
    op.drop_column('projects', 'updated_at')
    # ### end Alembic commands ###
